type Character implements Node {
	id: ID!
	name: String
	campaign: Campaign
	images: [Image!]!
	items: ItemCollection
	journal: [Journal!]!
	knowledge: [Lore!]!
	lore: [Lore!]!
	url: String
	slug: String

	owner: User
	permissions: Permissions
}

input CharacterInput {
	name: String

	# TODO: extend CharacterInput with system fields to allow stats to be added
}

extend type Query {
	character(slug: String, campaign: ID, user: ID, search: String): [Character]
}

extend type Mutation {
	character(character: CharacterInput, id: ID, campaign: ID, destroy: Boolean): Character # create / update character
}
