type Comment implements Node {
	id: ID!
	createdAt: DateTime
	body: String
	archived: Boolean
	character: Character
	children: [Comment!]!
}

type CommentSection {
	children: [Comment!]!
	total: Int
}

