type Calendar {
	year_length: Int
	weekdays: [String]
	months: [String]
	events: EventConnection
}

type EventConnection {
	years: [Year!]!
}

type Year {
	year: Int!
	months: [Month!]!

}

type Month {
	name: String
	weeks: [Week!]!
}

type Week {
	days: [Day]!
}

type Day {
	is_present: Boolean
	events: [Event]
}

type Event {
	timestamp: Int
	time: String
	name: String

}

extend type Query {
	calendar(campaign: ID! year: Int, month: Int, day: Int, start: Int, end: Int): Calendar
}
