type Image implements Node {
	id: ID!
	path: String
	node: Node
}

input ImageInput {
	file: Upload
}

extend type Mutation {
	image(image: ImageInput!, imageableType: String, imageable_id: ID): Image
}
