scalar DateTime

type Query {
	_: Boolean
}

type Mutation {
	_: Boolean
}

type Subscription {
	_: Boolean
	test: [Character]
}

interface Node {
	id: ID!
}

# 
type Permissions {
	read: Boolean
	write: Boolean
	own: Boolean
}
