scalar DateTime

# ==============================
# Queries
# ==============================

type Query {
	session: Session
	user(id: ID!): User

	character(slug: String, campaign: ID, user: ID, search: String): [Character]
	campaign(slug: String): [Campaign]
	item(slug: String, character: ID, search: String): ItemCollection
}

# ==============================
# Mutations
# ==============================

# type Mutation {
# 
# }

interface Node {
	id: ID!
}

type Session {
	user: User
	character: Character
	campaign: Campaign
}

# ==============================
# Types
# ==============================

type Image implements Node {
	id: ID!
	path: String
	node: Node
}

type User implements Node {
	id: ID!
	character: Character
	characters: [Character!]!
	email: String
	url: String
	username: String
}

type Character  implements Node {
	id: ID!
	name: String
	campaign: Campaign
	images: [Image!]!
	items: ItemCollection
	journal: [Journal!]!
	knowledge: [Lore!]!
	lore: [Lore!]!
	url: String
}

type Item implements Node {
	id: ID!
	name: String
	value: Float
	weight: Float
	quantity: Int
	total_value: Float
	total_weight: Float
	total_quantity: Int
	lore: [Lore!]!
	items: ItemCollection
	url: String
}

# Meta item information
type ItemCollection {
	items: [Item!]!
	total_quantity: Int
	total_weight: Float
	total_value: Float
}

type Lore implements Node {
	id: ID!
	topic: Node
	owner: User
	content: String
	url: String
}

type Journal implements Node {
	id: ID!
	title: String
	content: String
	url: String
}

type Campaign implements Node {
	id: ID!
	name: String
	system: System
	characters: [Character!]!
	lore: [Lore!]!
	quests: [Quest!]!
	url: String
}

enum QuestStatus {
	complete
	active
	failed
}

type Quest implements Node {
	id: ID!
	name: String
	description: String
	status: QuestStatus
	subquests: [Quest!]!
	comments: CommentSection
	# comments: [Comment!]!
	url: String
}

type Comment implements Node {
	id: ID!
	createdAt: DateTime
	body: String
	archived: Boolean
	character: Character
	children: [Comment!]!
}

type CommentSection {
	children: [Comment!]!
	total: Int
}

type System {
	name: String
	publisher: String
	year: Int
}
