query($detail: Boolean!, $slug: String, $user: ID, $campaign: ID, $search: String){
	character(slug: $slug, user: $user, campaign: $campaign, search: $search) {
		id
		name
		url
		slug
		images {
			path
		}
		items @include(if: $detail) {
			total_weight
			total_value
		}
		permissions {
			read
			write
			own
		}
	}
}
