query($slug: String, $character: ID, $search: String) {
	lore(slug: $slug, character: $character, search: $search) {
		id
		topic {
			id
			...on Character {
				name
				url
				images {
					path
				}
			}
			...on Item {
				name
				url
				owner {
					name
					url
				}
			
			}
		}
		owner {
			id
			name
			email
		}
		content
		url
	}
}

