query GetUser($detail: Boolean!, $slug: String, $search: String) {
	user(slug: $slug, search: $search) {
		id
		name
		url
		email
		characters @include(if: $detail) {
			name
			id
			url
			images {
				path
			}
		
		}
	
	}
}
